# Numpy

Numeric Python

Different kind of array and matrix

In [2]:
import numpy as np

In [3]:
import array

In [6]:
type(np.array([1,2,3,4,5]))    # nd-n dimensional array

numpy.ndarray

In [8]:
np.array([1,2,3,4,5,'sudh', 4+8j])     # upcasting 

array(['1', '2', '3', '4', '5', 'sudh', '(4+8j)'], dtype='<U11')

In [10]:
np.array([1,2,3,4,7.0])            # upcasting

array([1., 2., 3., 4., 7.])

In [11]:
np.array([[1,3],[3,4]])        # 2d array

array([[1, 3],
       [3, 4]])

In [12]:
np.array([[1,3],[3,4],[6,7]])

array([[1, 3],
       [3, 4],
       [6, 7]])

In [13]:
np.array([[1,3],[3,4],[6,7],[6,7,8]])

<ipython-input-13-6fa8cc0e4176>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[1,3],[3,4],[6,7],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7]), list([6, 7, 8])],
      dtype=object)

In [14]:
np.array([[[1,3],[3,4],[6,7]],[[1,3],[3,4],[6,7]]])

array([[[1, 3],
        [3, 4],
        [6, 7]],

       [[1, 3],
        [3, 4],
        [6, 7]]])

In [18]:
np.array([1,2,3], ndmin = 3)

array([[[1, 2, 3]]])

In [19]:
np.array([1,2,3], dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [21]:
np.array([(1,2),(4,5)])           # Can keep the data in the list or tuples

array([[1, 2],
       [4, 5]])

In [36]:
arr = np.array([(1,2),(4,5)], dtype= [('a','<i4'),('b','<i8')])   # i2 ,i4 ,i8 exist i2=16 bit, i4=32 bit, i8=64 bit

In [24]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [25]:
arr[0]

(1, 2)

In [26]:
arr[0][0]

1

In [31]:
type(arr[0][0])

numpy.int32

In [28]:
arr[0][1]

2

In [29]:
type(arr[0][1])

numpy.int64

In [37]:
arr = np.array([[1,3],[3,4]]) 

In [38]:
arr

array([[1, 3],
       [3, 4]])

In [40]:
arr[0][1]

3

In [41]:
type(arr[0][1])

numpy.int32

In [48]:
mat = np.mat(arr)           #can use either mat or matrix

In [44]:
l=[3,4,5,6,7]

In [45]:
np.array(l)

array([3, 4, 5, 6, 7])

In [46]:
np.asarray(l)

array([3, 4, 5, 6, 7])

In [47]:
np.asanyarray(l)

array([3, 4, 5, 6, 7])

In [50]:
np.asanyarray(mat)       #From line 48

matrix([[1, 3],
        [3, 4]])

In [51]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [52]:
issubclass(np.matrix, np.ndarray)    #Is matrixes are subclasses of ndarray

True

In [54]:
issubclass(np.ndarray,np.matrix)     #Is ndarray are subclasses of matrixes

False

In [55]:
arr

array([[1, 3],
       [3, 4]])

In [56]:
a = arr                 #shallow copy    ------ Interview questions

In [63]:
b = np.copy(arr)        #deepcopy        ------ Interview questions

In [59]:
arr[0][0] = 67          #array elements are mutable

In [60]:
arr

array([[67,  3],
       [ 3,  4]])

In [61]:
a 

array([[67,  3],
       [ 3,  4]])

In [62]:
b

array([[1, 3],
       [3, 4]])

In [64]:
arr[0:10]

array([[67,  3],
       [ 3,  4]])

In [65]:
arr[-1]

array([3, 4])

In [66]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [67]:
np.fromfunction(lambda i,j: i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [70]:
type(np.fromfunction(lambda i,j: i==j, (4,4)))

numpy.ndarray

In [72]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [73]:
np.fromfunction(lambda i,j: i**j, (4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [76]:
np.fromfunction(lambda i,j: i/j, (3,3))     #0/0 = nan, 1/0 = inf   --------- numpy handles such operations

<ipython-input-76-6f72fb908061>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j: i/j, (3,3))     #0/0 = nan, 1/0 = inf
<ipython-input-76-6f72fb908061>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j: i/j, (3,3))     #0/0 = nan, 1/0 = inf


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [92]:
gen = (i*i for i in range(5))         # range 

In [86]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [80]:
def test(x):
    yield x            # it help to generate some amount of data

In [81]:
test(5)

<generator object test at 0x000001F685FB1190>

In [93]:
gen

for i in gen:
    print(i)

0
1
4
9
16


In [88]:
np.fromiter(gen, dtype = int)

array([ 0,  1,  4,  9, 16])

In [90]:
np.fromiter(range(5), dtype = int)

array([0, 1, 2, 3, 4])

In [97]:
np.fromstring('1,2,3,4,5', sep = ',', dtype = int)

array([1, 2, 3, 4, 5])

In [100]:
np.fromstring('345 456 567 4564', sep = ' ', dtype = complex)

array([ 345.+0.j,  456.+0.j,  567.+0.j, 4564.+0.j])

In [118]:
l = [3,4,5,6,7,8]

In [119]:
arr = np.array(l)

In [108]:
arr1 = np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])

In [109]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [110]:
type(arr)

list

In [112]:
arr1.ndim       #IN how many dimension i will represent this data

2

In [113]:
arr1.size       #Total number of elements

12

In [114]:
arr1.shape

(3, 4)

In [115]:
arr1.dtype

dtype('int32')

In [116]:
arr

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]

In [120]:
arr.size

6

In [121]:
arr.shape

(6,)

In [122]:
arr.ndim

1

In [125]:
arr2 = np.array([[[1,2,3],[2,3,4]],[[1,2,3],[5,6,7]]])

In [126]:
arr2

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [5, 6, 7]]])

In [127]:
arr2.size

12

In [130]:
arr2.ndim     #3 dimension array

3

In [132]:
arr2.shape    # we have 2 array of size of  2 cross 3, data

(2, 2, 3)

In [143]:
arr4 = np.array([[[[1,2,3],[2,3,4]],[[1,2,3],[5,6,7]],[[1,2,3],[2,3,4]],[[1,2,3],[5,6,7]]]])   #4d data

In [144]:
arr4

array([[[[1, 2, 3],
         [2, 3, 4]],

        [[1, 2, 3],
         [5, 6, 7]],

        [[1, 2, 3],
         [2, 3, 4]],

        [[1, 2, 3],
         [5, 6, 7]]]])

In [145]:
arr4.shape   #

(1, 4, 2, 3)

In [146]:
arr4.ndim

4

In [151]:
list(range(6.6,9,3))

TypeError: 'float' object cannot be interpreted as an integer

In [150]:
np.arange(6.6)        # it is a substitute of a range function

array([0., 1., 2., 3., 4., 5., 6.])

In [160]:
np.arange(6.6,9,0.3)        #IN case of float it will include upperbound value

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [156]:
np.arange(9,6.6,-0.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [159]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [166]:
np.linspace(3,8)         # in between a line it generates a dataset of 50

array([3.        , 3.10204082, 3.20408163, 3.30612245, 3.40816327,
       3.51020408, 3.6122449 , 3.71428571, 3.81632653, 3.91836735,
       4.02040816, 4.12244898, 4.2244898 , 4.32653061, 4.42857143,
       4.53061224, 4.63265306, 4.73469388, 4.83673469, 4.93877551,
       5.04081633, 5.14285714, 5.24489796, 5.34693878, 5.44897959,
       5.55102041, 5.65306122, 5.75510204, 5.85714286, 5.95918367,
       6.06122449, 6.16326531, 6.26530612, 6.36734694, 6.46938776,
       6.57142857, 6.67346939, 6.7755102 , 6.87755102, 6.97959184,
       7.08163265, 7.18367347, 7.28571429, 7.3877551 , 7.48979592,
       7.59183673, 7.69387755, 7.79591837, 7.89795918, 8.        ])

In [167]:
np.linspace(1,2,5)     # in between a line it generates a dataset equally and how many data we need to generate, here it is 5

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [163]:
np.linspace(.1,.2,5)

array([0.1  , 0.125, 0.15 , 0.175, 0.2  ])

In [168]:
np.linspace(0,10,5)   

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [170]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [174]:
np.zeros((2,5,4,1))  # 4x1 , 5 array in 2 array

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [175]:
np.ones(4)

array([1., 1., 1., 1.])

In [178]:
np.ones((2,3,1))+5       # 3x1 , 2 such array

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [181]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [182]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [185]:
np.eye(3)            #identity matrix,  determinents equals to 1, all diagonals = 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [196]:
np.linspace([1,6], 4, endpoint=False, axis=1)  # The axis in the result to store the samples.  Relevant only if start
                                               # or stop are array-like.

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [200]:
np.logspace([2,3],5,axis=1)               # Return numbers spaced evenly on a log scale.

array([[   100.        ,    115.13953993,    132.57113656,
           152.64179672,    175.75106249,    202.35896477,
           232.99518105,    268.26957953,    308.88435965,
           355.64803062,    409.49150624,    471.48663635,
           542.86754393,    625.05519253,    719.685673  ,
           828.64277285,    954.09547635,   1098.54114199,
          1264.85521686,   1456.3484775 ,   1676.83293681,
          1930.69772888,   2222.99648253,   2559.5479227 ,
          2947.05170255,   3393.2217719 ,   3906.93993705,
          4498.43266897,   5179.47467923,   5963.62331659,
          6866.48845004,   7906.04321091,   9102.98177992,
         10481.13134155,  12067.92640639,  13894.95494373,
         15998.58719606,  18420.69969327,  21209.5088792 ,
         24420.53094549,  28117.68697974,  32374.57542818,
         37275.93720315,  42919.34260129,  49417.13361324,
         56898.66029018,  65512.85568596,  75431.20063355,
         86851.13737514, 100000.        ],
       [  100

In [202]:
np.logspace([2],[3] ,axis=0)  

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [203]:
d = np.linspace(4,7,40)

In [204]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [205]:
d.ndim

1

In [206]:
d.shape

(40,)

In [207]:
d.size

40

In [208]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [213]:
d.reshape(2,1,20)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
         4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
         6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [214]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [217]:
np.random.rand(3)  # Create an array of the given shape and populate it with
                   # random samples from a uniform distribution

array([0.99731936, 0.28705118, 0.8575663 ])

In [216]:
np.random.randn(5)   #Return a sample (or samples) from the "standard normal" distribution.

array([2.99244125, 0.44604775, 0.68915379, 0.43588113, 0.19018449])

In [221]:
np.random.randn(2,5,4)   #2 such array, 5 row 4 column

array([[[-1.5508191 ,  1.10316948,  1.89126262, -1.69545993],
        [ 0.35521047, -2.66423276,  0.95469515, -0.65031024],
        [-1.94962654,  1.44772963,  0.50512747, -0.77386892],
        [-0.52418706, -0.8824372 ,  0.55023876,  1.13857702],
        [ 0.56836818, -0.84586503, -1.12757361, -0.29490578]],

       [[-0.69739409, -0.65683983,  1.82104063,  1.13198603],
        [ 0.7057515 , -0.55860076, -0.25992745, -0.13453352],
        [ 1.64556513,  0.9132364 ,  1.04519552, -1.80485565],
        [-0.52840022, -0.55695388,  1.69445991, -0.54878229],
        [-0.44227221, -0.49225037, -0.79204809,  0.63065904]]])

In [227]:
np.random.randint(5,60, (4,4))   # Generates 4x4 matrix with random variables between 5 to 60

array([[ 8, 30, 51, 24],
       [ 6, 52,  7, 25],
       [59, 39, 50, 42],
       [42,  8, 50, 44]])

In [228]:
arr = np.random.randint(3,9,(3,3))

In [229]:
arr

array([[3, 8, 7],
       [4, 8, 5],
       [4, 4, 5]])

In [231]:
arr.reshape(1,9)     #1 row 9 column

array([[3, 8, 7, 4, 8, 5, 4, 4, 5]])

In [233]:
arr.reshape(9,1)    #9 row, 1 column

array([[3],
       [8],
       [7],
       [4],
       [8],
       [5],
       [4],
       [4],
       [5]])

In [234]:
arr.reshape(1,1,9)

array([[[3, 8, 7, 4, 8, 5, 4, 4, 5]]])

In [235]:
arr.reshape(3,3,1)

array([[[3],
        [8],
        [7]],

       [[4],
        [8],
        [5]],

       [[4],
        [4],
        [5]]])

In [239]:
arr.reshape(3,-4565461)    #-ve understands 

array([[3, 8, 7],
       [4, 8, 5],
       [4, 4, 5]])

In [240]:
arr.reshape(1,-5456465)

array([[3, 8, 7, 4, 8, 5, 4, 4, 5]])

In [241]:
arr.max()

8

In [242]:
arr.min()

3

In [246]:
arr = np.random.randint(4,100,(5,5))

In [247]:
arr

array([[11, 51, 28, 51, 55],
       [36,  4, 45, 57, 54],
       [12, 43, 76, 18, 57],
       [11, 86, 47, 28, 87],
       [29,  4, 42, 38, 30]])

In [249]:
arr[3:, 3:]     # Extract data from arr

array([[28, 87],
       [38, 30]])

In [251]:
arr[1:,[1,3]]     #Looking for all rows from 1, columns 1 and 3

array([[ 4, 57],
       [43, 18],
       [86, 28],
       [ 4, 38]])

In [254]:
arr>10

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [255]:
arr[arr>10]

array([11, 51, 28, 51, 55, 36, 45, 57, 54, 12, 43, 76, 18, 57, 11, 86, 47,
       28, 87, 29, 42, 38, 30])

In [256]:
arr * arr

array([[ 121, 2601,  784, 2601, 3025],
       [1296,   16, 2025, 3249, 2916],
       [ 144, 1849, 5776,  324, 3249],
       [ 121, 7396, 2209,  784, 7569],
       [ 841,   16, 1764, 1444,  900]])

In [257]:
arr1 = np.random.randint(2,4,(3,3))

In [262]:
arr2 = np.random.randint(2,4,(3,3))

In [264]:
arr1 * arr2        # Not matrix multiplication only element multiplication 
                   # dimension of both matrix should be same

array([[6, 9, 4],
       [6, 6, 6],
       [6, 4, 6]])

In [265]:
arr1@arr2        # MAtrix multiplication

array([[21, 19, 19],
       [19, 16, 17],
       [19, 16, 16]])

In [266]:
arr/0

<ipython-input-266-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [267]:
arr**2

array([[ 121, 2601,  784, 2601, 3025],
       [1296,   16, 2025, 3249, 2916],
       [ 144, 1849, 5776,  324, 3249],
       [ 121, 7396, 2209,  784, 7569],
       [ 841,   16, 1764, 1444,  900]], dtype=int32)

In [269]:
# Broadcasting

arr = np.zeros((3,4))

In [270]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [278]:
a = np.array([1,2,3,4])

In [280]:
arr + a          # row and column should be same

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [275]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [286]:
b = np.array([5,6,3])

In [287]:
b

array([5, 6, 3])

In [288]:
b.reshape(3,1) + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [3., 3., 3., 3.]])

In [291]:
b = np.array([[5,6,3]])

In [294]:
b.T + arr              # Column wise broadcasting operations

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [3., 3., 3., 3.]])

In [295]:
arr = np.random.rand(5,4)

In [296]:
arr

array([[0.40383839, 0.92921133, 0.44658053, 0.7715154 ],
       [0.2967584 , 0.36322191, 0.27650568, 0.84297045],
       [0.03482311, 0.90112101, 0.84949973, 0.60690266],
       [0.89631747, 0.04714222, 0.17296847, 0.33867284],
       [0.92334706, 0.26819335, 0.75150447, 0.88286403]])

In [297]:
np.sqrt(arr)

array([[0.6354828 , 0.96395608, 0.66826681, 0.87835949],
       [0.54475535, 0.60267895, 0.52583808, 0.91813422],
       [0.18660952, 0.94927394, 0.9216831 , 0.77903958],
       [0.94674044, 0.2171226 , 0.41589478, 0.58195605],
       [0.9609095 , 0.51787388, 0.86689358, 0.93960844]])

In [298]:
np.exp(arr)

array([[1.4975619 , 2.53251108, 1.56295854, 2.16304164],
       [1.34549018, 1.43795493, 1.31851445, 2.32325786],
       [1.03543654, 2.46236189, 2.33847669, 1.83473978],
       [2.4505622 , 1.04827109, 1.18882862, 1.40308424],
       [2.5177032 , 1.30759994, 2.12018738, 2.41781449]])

In [299]:
np.log10(arr)

array([[-0.3937924 , -0.0318855 , -0.35010022, -0.1126554 ],
       [-0.52759699, -0.43982796, -0.55829594, -0.07418765],
       [-1.45813239, -0.04521689, -0.07083675, -0.21688096],
       [-0.04753814, -1.32658995, -0.76203306, -0.47021963],
       [-0.03463503, -0.57155199, -0.12406843, -0.05410618]])

In [301]:
arr1 = np.random.randint(2,5, (5,5))

In [307]:
np.log2(arr1)

array([[1.5849625, 1.5849625, 1.5849625, 2.       , 1.5849625],
       [2.       , 1.       , 1.5849625, 1.5849625, 2.       ],
       [1.       , 2.       , 2.       , 1.       , 2.       ],
       [2.       , 1.       , 1.       , 2.       , 1.5849625],
       [1.5849625, 1.       , 1.5849625, 1.       , 1.       ]])

In [303]:
arr1

array([[3, 3, 3, 4, 3],
       [4, 2, 3, 3, 4],
       [2, 4, 4, 2, 4],
       [4, 2, 2, 4, 3],
       [3, 2, 3, 2, 2]])

In [308]:
np.random.seed(13)

In [320]:
np.random.seed(30)      # Rule based generate data based on rules 
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])